Repository monkeyWie/proxyee, pull requests merged in 2022-02, with the labels that each got.

#196 build: upgrade bc version
  README.md
  README_zh-CN.md
  pom.xml
Labels: dependencies

#199 Add suitable protected/etc methods in HttpProxyServerHandler
  src/main/java/com/github/monkeywie/proxyee/handler/HttpProxyServerHandler.java
Labels: enhancement

#203 feat: connect mode handle http
  README.md
  README_zh-CN.md
  pom.xml
  src/main/java/com/github/monkeywie/proxyee/handler/HttpProxyServerHandler.java
  src/test/java/com/github/monkeywie/proxyee/NormalHttpProxyServer.java
Labels: feature

#206 fix isuse #205
  src/main/java/com/github/monkeywie/proxyee/server/HttpProxyServer.java
  src/main/java/com/github/monkeywie/proxyee/server/HttpProxyServerConfig.java
  src/test/java/com/github/monkeywie/proxyee/InterceptFullResponseProxyServer.java
Labels: feature
